spring: 
  profiles: 
    active: dev # 激活开发环境配置 
--- 
server:
  port: 7001
 
spring:
  profiles: dev # 生产环境 

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com/eureka
  instance:
    prefer-ip-address:  true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}


zuul:
  routes:
    provider-product:
      path: /product/**
      serviceId: microservice-product-config
      stripPrefix: false
    consumer-product:
      path: /consumer/**
      serviceId: microservice-consumer
      stripPrefix: false
--- 
server: 
  port: 7001 
spring: 
  profiles: prod # 生产环境 

    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com/eureka
  instance:
    prefer-ip-address:  true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}


zuul:
  routes: 
    provider-product:
      path: /product/**
      serviceId: microservice-product-config
      stripPrefix: false
    consumer-product:
      path: /consumer/**
      serviceId: microservice-consumer
      stripPrefix: false
      
