spring: 
    profiles: 
        active: dev # 激活开发环境配置 
--- 
server:
  port: 7001
 
spring:
	profiles: dev # 生产环境 
  application:
    name: microservice-zuul-gateway
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
    	defaultZone: http://eureka6001.com:6001/eureka
  instance:
    prefer-ip-address:  true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}


zuul:
  routes:
  	microservice-product: /product/** 

--- 
server: 
    port: 7001 
spring: 
	profiles: prod # 生产环境 
  application: 
		name: microservice-product-config
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
    	defaultZone: http://eureka6001.com:6001/eureka
  instance:
    prefer-ip-address:  true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}


zuul:
  routes:
  	microservice-product: /product/** 
