emp:
    name: 汤姆憨克斯
server: 
    port: 8001 
mybatis: 
    config-location: classpath:mybatis/mybatis.cfg.xml 
    type-aliases-package: com.springcloud.entities 
    mapper-locations: classpath:mybatis/mapper/**/*.xml 
spring: 
    profiles: dev # 开发环境 
    asdas: 5555
    application: 
        name: microservice-product-config-bus
    datasource: 
        type: com.alibaba.druid.pool.DruidDataSource 
        driver-class-name: com.mysql.cj.jdbc.Driver 
        url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        dbcp2: 
            min-idle: 5 
            initial-size: 5 
            max-total: 5 
            max-wait-millis: 150 
eureka: 
    client: 
        registerWithEureka: true 
        fetchRegistry: true 
        serviceUrl: 
            defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com/eureka
    instance: 
        instanceId: ${spring.application.name}:${server.port} 
        prefer-ip-address: true 
management:
  endpoints:
    web:
      exposure:
        include: "*"
